services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m
    networks:
      - proxy
      - plausible_network

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1",
        ]
      start_period: 1m
    networks:
      - proxy
      - plausible_network

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      - BASE_URL=https://plausible.bryanwills.dev
      - SECRET_KEY_BASE=AFzDdn66fIg5hbV6+QyLn3JM8hRYXGcXZYzL+wzhOEiLqPVG4mScBOggw28PqtUrsn5PYhxflRZkV84qNxOVUA==
      - DATABASE_URL=postgres://postgres:postgres@plausible_db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible
      - DISABLE_REGISTRATION=true
      - ADMIN_USER_EMAIL=bryanwi09@gmail.com
      - ADMIN_USER_NAME=Admin
      - ADMIN_USER_PWD=BigBrainAdmin2025!
    networks:
      - proxy
      - plausible_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.plausible-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plausible-http.entrypoints=web"
      - "traefik.http.routers.plausible-http.middlewares=plausible-https-redirect"
      - "traefik.http.routers.plausible-http.rule=Host(`plausible.bryanwills.dev`)"
      - "traefik.http.routers.plausible-secure.entrypoints=websecure"
      - "traefik.http.routers.plausible-secure.rule=Host(`plausible.bryanwills.dev`)"
      - "traefik.http.routers.plausible-secure.service=plausible"
      - "traefik.http.routers.plausible-secure.tls=true"
      - "traefik.http.routers.plausible-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:

networks:
  proxy:
    external: true
  plausible_network:
