services:
  loki:
    image: grafana/loki:3.5.3
    container_name: loki
    restart: unless-stopped
    command:
      - "-config.file=/etc/loki/loki-config.yaml"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOSTNAME=loki.bryanwills.dev
      - HOME=/root
    volumes:
      - /home/bryanwi09/docker/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - /home/bryanwi09/docker/loki/data:/loki
      - /etc/localtime:/etc/localtime
    ports:
      - "3100:3100"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.bryanwills.dev`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=letsencrypt"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.middlewares.loki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.loki-http.rule=Host(`loki.bryanwills.dev`)"
      - "traefik.http.routers.loki-http.entrypoints=web"
      - "traefik.http.routers.loki-http.middlewares=loki-https-redirect"
    networks:
      - proxy

networks:
  proxy:
    external: true
