version: "3.9"
services:
  it-tools:
    image: "corentinth/it-tools:latest"
    restart: unless-stopped
    container_name: it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.entrypoints=http"
      - "traefik.https.routers.it-tools.rule=Host(`it-tools.bryanwills.dev`)"
      - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.it-tools.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.it-tools-secure.entrypoints=https"
      - "traefik.http.routers.it-tools-secure.rule=Host(`it-tools.bryanwills.dev`)"
      - "traefik.http.routers.it-tools-secure.tls=true"
      - "traefik.http.routers.it-tools-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.it-tools-secure.service=it-tools"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
