version: "3.9"
services:
  it-tools:
    image: "corentinth/it-tools:latest"
    restart: unless-stopped
    container_name: it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.it-tools-http.entrypoints=web"
      - "traefik.http.routers.it-tools-http.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.it-tools-http.rule=Host(`it-tools.bryanwills.dev`)"
      - "traefik.http.routers.it-tools-secure.entrypoints=websecure"
      - "traefik.http.routers.it-tools-secure.rule=Host(`it-tools.bryanwills.dev`)"
      - "traefik.http.routers.it-tools-secure.service=it-tools"
      - "traefik.http.routers.it-tools-secure.tls=true"
      - "traefik.http.routers.it-tools-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
