# version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOSTNAME=07e14871300e
      - DOMAIN=https://vault.bryanwills.dev
      - WEBSOCKET_ENABLED=true
      - SENDS_ALLOWED=true
      - PASSWORD_ITERATIONS=500000
      - ROCKET_PROFILE=release
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=80
      - DEBIAN_FRONTEND=noninteractive
      - HOME=/root
    volumes:
      - /home/bryanwi09/docker/vaultwarden:/data
    labels:
      - "com.docker.compose.config-hash=6f1956a11a27da7589ad6bb8edc03250847b0785e03910df7cde91bee46e5a35"
      - "com.docker.compose.container-number=1"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=vaultwarden"
      - "com.docker.compose.project.config_files=docker-compose.yml"
      - "com.docker.compose.project.working_dir=/home/bryanwi09/docker/vaultwarden"
      - "com.docker.compose.service=vaultwarden"
      - "com.docker.compose.version=1.29.2"
      - "org.opencontainers.image.created=2025-05-26T21:22:55+00:00"
      - "org.opencontainers.image.description=Unofficial Bitwarden compatible server written in Rust - 1.34.1"
      - "org.opencontainers.image.documentation=https://github.com/dani-garcia/vaultwarden/wiki"
      - "org.opencontainers.image.licenses=AGPL-3.0-only"
      - "org.opencontainers.image.revision=53f58b14d5626abfcefd52586ec9e78d067a2334"
      - "org.opencontainers.image.source=https://github.com/dani-garcia/vaultwarden"
      - "org.opencontainers.image.url=https://github.com/dani-garcia/vaultwarden"
      - "org.opencontainers.image.version=1.34.1"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`vault.bryanwills.dev`)"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
      - "traefik.http.routers.vaultwarden-secure.tls=true"
      - "traefik.http.routers.vaultwarden-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.vaultwarden-http.entrypoints=web"
      - "traefik.http.routers.vaultwarden-http.middlewares=vaultwarden-https-redirect"
      - "traefik.http.routers.vaultwarden-http.rule=Host(`vault.bryanwills.dev`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
