entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: bryanwi09@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: true

api:
  dashboard: true

log:
  level: DEBUG
