services:
  syslog-server:
    image: balabit/syslog-ng:latest
    container_name: syslog-server
    restart: unless-stopped
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./config:/etc/syslog-ng
      - ./logs:/var/log
    networks:
      - proxy
    # No Traefik labels needed - syslog-server is not a web service

networks:
  proxy:
    external: true