version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    # uncomment if you do not want to run as root
    #user: 1000:1000
    # uncomment if you are not using a reverse proxy
    #ports:
    #  - 3000:3000
    volumes:
      - /home/bryanwi09/docker/Homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage-http.entrypoints=web"
      - "traefik.http.routers.homepage-http.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-http.rule=Host(`homepage.bryanwills.dev`)"
      - "traefik.http.routers.homepage-secure.entrypoints=websecure"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.bryanwills.dev`)"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
