---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- My First Group:
    - My First Service:
        href: https://bryanwills.dev/
        description: Homepage is awesome

    - Traefik:
        icon: traefik.png
        href: "http://traefik.bryanwills.dev"
        description: Reverse Proxy
        #server: my-docker # The docker server that was configured
        container: traefik # The name of the container you'd like to connect
        widget:
          type: traefik
          url: https://traefik.bryanwills.dev
          #username: admin
          #password: gT8ni3iX6QkKreWfAdYKe4xqVsaMRUQ4GG7xn59Q

    - DocMost:
        #icon: pi-hole.png
        href: "http://docs.bryanwills.dev"
        description: DocMost documentation site
        #server: my-docker # The docker server that was configured
        container: docmost # The name of the container you'd like to connect
        widget:
          type: docmost
          #url: http://192.168.8.2
          #key: 73T8oBs9MFKLVAC3mAs2KQbWSsqA7oe2PN9r9H4TQWg2TXNAdq4ZPzvy8oEv

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
