# OpenGist Configuration File
# NOTE: This file references environment variables that are loaded from .env
# The docker-compose.yml passes these values to the container

log-level: info
log-output: stdout
external-url: https://gist.bryanwills.dev
opengist-home: /opengist
secret-key: ${SECRET_KEY}
db-uri: opengist.db
index: bleve
sqlite.journal-mode: WAL
http.host: 0.0.0.0
http.port: 6157
http.git-enabled: true
ssh.git-enabled: true
ssh.host: 0.0.0.0
ssh.port: 2222
ssh.external-domain: gist.bryanwills.dev
github.client-key: ${GITHUB_OAUTH_CLIENT_ID}
github.secret: ${GITHUB_OAUTH_CLIENT_SECRET}
custom.name: Gist