---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/bryanwills/
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com/

- Infra Docs:
    - Traefik Docs:
        - abbr: TR
          href: https://doc.traefik.io/traefik/
    - Homepage Docs:
        - abbr: HP
          href: https://gethomepage.dev/
